[project]
name = "gwfast"
version = "1.1.2"
description = "A fisher matrix python package for GW studies"
authors = [
    { name = "Francesco Iacovelli", email = "francesco.iacovelli@unige.ch" },
    { name = "Michele Mancarella", email = "michele.mancarella@unige.ch" },
]
requires-python = ">=3.9"
readme = "README.md"
license = "GPL-3.0-only" #"GNU GPLv3"
maintainers = [{ name = "Niccolo' Muttoni", email = "niccolo.muttoni@unige.ch" }]
keywords = [
    "python",
    "automatic-differentiation",
    "gravitational-waves",
    "fisher-information",
    "jax",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy<=1.26.4",
    "scipy>=1.6.3",
    "astropy~=6.0.0",
    "h5py>=3.2.1,<4",
    "mpmath>=1.2.1,<2",
    "numdifftools==0.9.41",
    "schwimmbad>=0.3.2,<0.4",
    "jax[cpu]>=0.4.26, <=0.4.30",
    "lalsuite>=7.26.4",
    "ipython>=8.18.1",
]

[project.optional-dependencies]
lal = ["lalsuite"]
teobresum = ["teobresums"]
docs = [
    "sphinx==5.3.0",
    "sphinx_rtd_theme>=1.1.1",
    "nbsphinx>=0.8.10",
    "myst-parser>=0.18.1,<0.19",
    "sphinx-copybutton>=0.5.1,<0.6",
    "readthedocs-sphinx-search>=0.1.2,<0.2",
    "docutils>=0.17.1,<0.18",
]

[project.urls]
Repository = "https://github.com/CosmoStatGW/gwfast"
Documentation = "https://gwfast.readthedocs.io/en/latest/"

[dependency-groups]
dev = ["matplotlib"]

[tool.hatch.build.targets.sdist]
include = [
    "/gwfast",
    "/run",
    "/WFfiles",
    "/psds",
]

[tool.hatch.build.targets.sdist.force-include]
WFfiles = "WFfiles"
psds = "psds"
"psds/ce_strain" = "psds/ce_strain"
"psds/ET_designs_comparison_paper" = "psds/ET_designs_comparison_paper"
"psds/LVC_O1O2O3" = "psds/LVC_O1O2O3"
"psds/observing_scenarios_paper" = "psds/observing_scenarios_paper"
"psds/unofficial_curves_all_dets" = "psds/unofficial_curves_all_dets"
"gwfast/.patch" = "gwfast/.patch"

[tool.hatch.build.targets.wheel]
packages = ["gwfast", "run"]
#include = [
#    "gwfast",
#    "run",
#]

[tool.hatch.build.targets.wheel.shared-data]
# This ensures data folders are included in the installation
"WFfiles" = "WFfiles"
"psds" = "psds"

[tool.hatch.build.targets.wheel.force-include]
WFfiles = "WFfiles"
psds = "psds"
"psds/ce_strain" = "psds/ce_strain"
"psds/ET_designs_comparison_paper" = "psds/ET_designs_comparison_paper"
"psds/LVC_O1O2O3" = "psds/LVC_O1O2O3"
"psds/observing_scenarios_paper" = "psds/observing_scenarios_paper"
"psds/unofficial_curves_all_dets" = "psds/unofficial_curves_all_dets"
"gwfast/.patch" = "gwfast/.patch"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
